/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import config.dbConnector;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class addproperty extends javax.swing.JFrame {

    /**
     * Creates new form addproperty
     */
    public addproperty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonPANE = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        upd = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        headerPANE = new javax.swing.JPanel();
        Appname1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        Appname3 = new javax.swing.JLabel();
        idshet = new javax.swing.JTextField();
        addPANE = new javax.swing.JPanel();
        forgotpass3 = new javax.swing.JLabel();
        forgotpass6 = new javax.swing.JLabel();
        forgotpass9 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        loc = new javax.swing.JTextField();
        rate = new javax.swing.JComboBox<>();
        pt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        view = new javax.swing.JLabel();
        remove = new javax.swing.JButton();
        forgotpass10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        pn = new javax.swing.JTextField();
        forgotpass11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(243, 234, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(146, 80, 80), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonPANE.setBackground(new java.awt.Color(146, 80, 80));
        buttonPANE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPANEMouseClicked(evt);
            }
        });
        buttonPANE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(214, 223, 231));
        add.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(134, 163, 194));
        add.setText("ADD");
        add.setBorder(null);
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        buttonPANE.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 240, 30));

        upd.setBackground(new java.awt.Color(214, 223, 231));
        upd.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        upd.setForeground(new java.awt.Color(134, 163, 194));
        upd.setText("UPDATE");
        upd.setBorder(null);
        upd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        upd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updMouseClicked(evt);
            }
        });
        upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updActionPerformed(evt);
            }
        });
        buttonPANE.add(upd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 130, 30));

        jButton5.setBackground(new java.awt.Color(214, 223, 231));
        jButton5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(134, 163, 194));
        jButton5.setText("CLEAR");
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        buttonPANE.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 30));

        jPanel2.add(buttonPANE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 580, 50));

        headerPANE.setBackground(new java.awt.Color(146, 80, 80));
        headerPANE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Appname1.setBackground(new java.awt.Color(0, 0, 0));
        Appname1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        Appname1.setForeground(new java.awt.Color(183, 206, 229));
        Appname1.setText("USER FORM");
        headerPANE.add(Appname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BACK >>");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        headerPANE.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        id1.setForeground(new java.awt.Color(255, 255, 255));
        id1.setText("USER");
        id1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        id1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                id1MouseEntered(evt);
            }
        });
        headerPANE.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 50, -1));

        Appname3.setBackground(new java.awt.Color(0, 0, 0));
        Appname3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Appname3.setForeground(new java.awt.Color(183, 206, 229));
        Appname3.setText("iBook");
        headerPANE.add(Appname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        idshet.setEditable(false);
        idshet.setBackground(new java.awt.Color(146, 80, 80));
        idshet.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        idshet.setForeground(new java.awt.Color(255, 255, 255));
        idshet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        headerPANE.add(idshet, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 20, -1));

        jPanel2.add(headerPANE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 50));

        addPANE.setBackground(new java.awt.Color(243, 234, 234));
        addPANE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgotpass3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        forgotpass3.setForeground(new java.awt.Color(102, 102, 102));
        forgotpass3.setText("Property Type");
        addPANE.add(forgotpass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, -1));

        forgotpass6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        forgotpass6.setForeground(new java.awt.Color(102, 102, 102));
        forgotpass6.setText("Property Name");
        addPANE.add(forgotpass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        forgotpass9.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        forgotpass9.setForeground(new java.awt.Color(102, 102, 102));
        forgotpass9.setText("Location");
        addPANE.add(forgotpass9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        price.setBackground(new java.awt.Color(243, 234, 234));
        price.setAlignmentX(0.0F);
        price.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(146, 80, 80)));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        addPANE.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 30));

        loc.setBackground(new java.awt.Color(243, 234, 234));
        loc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(146, 80, 80)));
        loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locActionPerformed(evt);
            }
        });
        addPANE.add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 320, 30));

        rate.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        rate.setForeground(new java.awt.Color(134, 163, 194));
        rate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "/night", "/day" }));
        rate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(183, 206, 229), 2, true));
        rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateActionPerformed(evt);
            }
        });
        addPANE.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 70, 30));

        pt.setBackground(new java.awt.Color(243, 234, 234));
        pt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(146, 80, 80)));
        pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptActionPerformed(evt);
            }
        });
        addPANE.add(pt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 150, 30));

        jPanel3.setBackground(new java.awt.Color(248, 243, 243));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(146, 80, 80), 2));

        view.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        view.setForeground(new java.awt.Color(102, 102, 102));
        view.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        view.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                viewFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                viewFocusLost(evt);
            }
        });
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );

        addPANE.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 190));

        remove.setBackground(new java.awt.Color(214, 223, 231));
        remove.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 12)); // NOI18N
        remove.setForeground(new java.awt.Color(134, 163, 194));
        remove.setText("REMOVE IMAGE");
        remove.setBorder(null);
        remove.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
        });
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        addPANE.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 110, 30));

        forgotpass10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        forgotpass10.setForeground(new java.awt.Color(102, 102, 102));
        forgotpass10.setText("PHP");
        addPANE.add(forgotpass10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane2.setViewportView(desc);

        addPANE.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 320, 60));

        pn.setBackground(new java.awt.Color(243, 234, 234));
        pn.setAlignmentX(0.0F);
        pn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(146, 80, 80)));
        pn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnActionPerformed(evt);
            }
        });
        addPANE.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 30));

        forgotpass11.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        forgotpass11.setForeground(new java.awt.Color(102, 102, 102));
        forgotpass11.setText("Description");
        addPANE.add(forgotpass11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jPanel2.add(addPANE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 540, 280));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(243, 234, 234));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        dbConnector dbc = new dbConnector();
        String php = price.getText(), pname = pn.getText(), ptype = pt.getText(),
        location = loc.getText(), descr = desc.getText(),
        ratee = rate.getSelectedItem().toString(), status = "Available";

        if (php.isEmpty() || pname.isEmpty() || ptype.isEmpty() || location.isEmpty() || descr.isEmpty() || ratee.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
            return;
        }else if (rate == null) {
            JOptionPane.showMessageDialog(null, "Please select a rate.");
        }else{

            if (dbc.insertData("INSERT INTO tbl_prop (propname, lname, mname, u_name, u_email, u_address, u_pass, u_role, u_phone, u_status, pfp) VALUES ('"
                +php.getText() + "', '"
                +pname.getText() + "', '"
                +ptype.getText() + "', '"
                +location.getText() + "', '"
                +descr.getText() + "', '"
                +rate.getSelectedItem() + "', '"
                +destination+
                "')") > 0) {

            try{
                Files.copy(selectedFile.toPath(), new File(destination).toPath(), StandardCopyOption.REPLACE_EXISTING);

                JOptionPane.showMessageDialog(null,"Registered Successfully.");
                uform users = new uform();
                users.setVisible(true);
                this.dispose();

            }catch(IOException ex){
                System.out.println("Insert Image Error: "+ex);
            }
        }else {
            JOptionPane.showMessageDialog(null,"Registration Failed..");
        }
        }
    }//GEN-LAST:event_addActionPerformed

    private void updMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updMouseClicked

    private void updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updActionPerformed
        String fname = price.getText(), lname = ln.getText(), username = u_name.getText(),
        email = u_email.getText(), address = loc.getText(),
        password = pass.getText().trim(), contact = phone.getText(),
        role = u_role.getSelectedItem().toString(), status = rate.getSelectedItem().toString();

        if (fname.isEmpty() || lname.isEmpty() || username.isEmpty() || email.isEmpty() || password.isEmpty() || address.isEmpty() || contact.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
        }else if (password.length() < 8 ) {
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters.");
        }else if(updCheck()){
            System.out.println("[ERROR]Duplicate Found.");
        }else{
            dbConnector dbc = new dbConnector();
            dbc.updateData("UPDATE tbl_user SET fname = '"+price.getText()+"', lname = '"+ln.getText()+"', mname = '"+pt.getText()+"',               "
                +    "u_email = '"+u_email.getText()+"', u_phone = '"+phone.getText()+"', u_address = '"+loc.getText()+"',             "
                +    "u_name = '"+u_name.getText()+"', u_role = '"+u_role.getSelectedItem()+"', u_status = '"+rate.getSelectedItem()+"',  "
                +    "u_pass = '"+pass.getText()+"', pfp = '"+destination+"' WHERE userID = '"+idshet.getText()+"' ");

            if(destination.isEmpty()){
                File existingFile = new File(oldpath);
                if(existingFile.exists()){
                    existingFile.delete();
                }
            }else{
                if(!(oldpath.equals(path))){
                    imageUpdater(oldpath, path);
                }
            }

            JOptionPane.showMessageDialog(null, "Updated Successfully.");

            userlist.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_updActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        price.setText(""); ln.setText(""); u_name.setText(""); u_email.setText(""); loc.setText("");
        pass.setText(""); phone.setText(""); pt.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void buttonPANEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPANEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPANEMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        userlist.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void id1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_id1MouseClicked

    private void id1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_id1MouseEntered

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locActionPerformed

    private void rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateActionPerformed

    private void ptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptActionPerformed

    }//GEN-LAST:event_ptActionPerformed

    private void viewFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_viewFocusGained

    }//GEN-LAST:event_viewFocusGained

    private void viewFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_viewFocusLost

    }//GEN-LAST:event_viewFocusLost

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                selectedFile = fileChooser.getSelectedFile();
                destination = "src/images/" + selectedFile.getName();
                path  = selectedFile.getAbsolutePath();

                if(FileExistenceChecker(path) == 1){
                    JOptionPane.showMessageDialog(null, "File Already Exist, Rename or Choose another!");
                    destination = "";
                    path="";
                }else{
                    view.setIcon(ResizeImage(path, null, view));
                    remove.setEnabled(true);
                }
            } catch (Exception ex) {
                System.out.println("File Error!");
            }
        }
    }//GEN-LAST:event_viewMouseClicked

    private void viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseEntered
        Color vieww = new Color(204,204,204);
        view.setForeground(vieww);
    }//GEN-LAST:event_viewMouseEntered

    private void viewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseExited
        Color viewww = new Color(102,102,102);
        view.setForeground(viewww);
    }//GEN-LAST:event_viewMouseExited

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_removeMouseClicked

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        remove.setEnabled(false);
        view.setEnabled(true);
        view.setIcon(null);
        destination = "";
        path = "";
    }//GEN-LAST:event_removeActionPerformed

    private void pnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addproperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addproperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addproperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addproperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addproperty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Appname1;
    private javax.swing.JLabel Appname3;
    public javax.swing.JButton add;
    private javax.swing.JPanel addPANE;
    private javax.swing.JPanel buttonPANE;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel forgotpass10;
    private javax.swing.JLabel forgotpass11;
    private javax.swing.JLabel forgotpass3;
    private javax.swing.JLabel forgotpass6;
    private javax.swing.JLabel forgotpass9;
    private javax.swing.JPanel headerPANE;
    private javax.swing.JLabel id1;
    public javax.swing.JTextField idshet;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField loc;
    public javax.swing.JTextField pn;
    public javax.swing.JTextField price;
    public javax.swing.JTextField pt;
    public javax.swing.JComboBox<String> rate;
    public javax.swing.JButton remove;
    public javax.swing.JButton upd;
    public javax.swing.JLabel view;
    // End of variables declaration//GEN-END:variables
}
